version: '3.9'

services:
  blotto-game:
    build: .
    container_name: blotto-game
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=blotto_db
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=password
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mongodb_network
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh blotto_db -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  mongo-data:

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network
