version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mongodb_network
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh blotto_db -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    restart: "no"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://blotto_db:27017/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/status || exit -1
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5


#  mongo-express:
#    image: mongo-express:latest
#    container_name: mongo-express
#    restart: always
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_SERVER: 'mongodb'
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: password
#    ports:
#      - "8081:8081"
#    networks:
#      - mongodb_network
#    depends_on:
#      - mongodb

volumes:
  mongo-data:

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network
